pipeline {
    agent none

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/jksmth/container.image.jenkins.git'
            }
        }

       stage('Build') {
            agent {
                kubernetes {
                    yamlFile 'kaniko/pod.yaml'
                }
            }
            
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    script {
                        sh  '''
                            /kaniko/executor \
                            --dockerfile Dockerfile \
                            --context `pwd`/ \
                            --verbosity debug \
                            --destination jksmth/test-build:latest
                        '''
                    }
                }
            }
        }
    }
}