pipeline {
    agent none

    stages {
       stage('Build') {
            agent {
                kubernetes {
                    yamlFile 'kaniko/pod.yaml'
                }
            }
            
            steps {
                container(name: 'executor', shell: '/busybox/sh') {
                    script {
                        sh  '''
                            /kaniko/executor \
                            --dockerfile Dockerfile \
                            --context `pwd`/ \
                            --verbosity debug \
                            --destination jksmth/test-build:latest
                        '''
                    }
                }
            }
        }
    }
}