---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-build: app-build
    some-label: "build-app-${BUILD_NUMBER}"
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.8.0-debug
      imagePullPolicy: IfNotPresent
      command:
        - /busybox/cat
      resources:
        limits: {}
        requests:
          memory: "256Mi"
          cpu: "100m"
      tty: true
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: docker-credentials
              items:
                - key: .dockerconfigjson
                  path: config.json
